networks:
  my-network:

volumes:
  mysqldata:

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/app/public
    networks:
      - my-network
    restart: unless-stopped

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
    networks:
      - my-network
    restart: unless-stopped

  db:
    image: mysql:latest
    env_file: .env
    networks:
      - my-network
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql

  db-admin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    env_file: .env
    networks:
      - my-network
    ports:
      - "8081:80"
